version: "3.8"
services:
  dotnet_core_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: DotnetCoreApp
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
    ports:
      - "3000:80"
    networks:
      - back-tier

  postgres_db:
    image: postgres:14.1-alpine
    container_name: postgresDB
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - back-tier

networks:
  back-tier:

volumes:
  db:
    driver: local
