version: "3.8"
services:
  dotnet_core_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: DotnetCoreApp
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
    depends_on:
      mssql:
        condition: service_started
    ports:
      - "3000:80"
    networks:
      - back-tier

  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: SqlServerDatabase
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    ports:
      - 1433:1433
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - back-tier

networks:
  back-tier:

volumes:
  sql_data:
    driver: local
